Feature/character list
isdi-coders-2023/ConejosVoladores-202309-bcn pull request #16
Opened 2023-10-31 17:49 UTC by bigotes0invisibles

2023-10-31 18:11 UTC, annarosesmarti submitted a review, later dismissed

2023-10-31 18:11 UTC, annarosesmarti commented on src/components/CharacterList/CharacterList.tsx
requerimos el map ya? cuando no tenemos nada a quien aplicarle el map aun?
como no lo tengo nada claro te doy el ok, pero me cuentas mañana porfa!

2023-10-31 19:21 UTC, barbara28bgb reviewed
le estas pasando el objeto characters vacio ??
estas pudiendo acceder al Context en el test sin testear el Hook?

2023-10-31 20:35 UTC, bigotes0invisibles commented on src/components/CharacterList/CharacterList.tsx
Se pueden inicializar las listas y los ítems o <li>

2023-10-31 20:38 UTC, bigotes0invisibles commented
Se pueden comprobar La inicialización de charaterlist junto con el contexto de personajes

2023-11-01 14:48 UTC, barbara28bgb reviewed
Puedes revisar si los GlobalStyle son necesarios, en ese caso me explicas por q si

2023-11-01 14:48 UTC, barbara28bgb commented on src/components/CharacterList/CharaterList.test.tsx
Puedes revisar si los GlobalStyle son necesarios, en ese caso me explicas por q si

2023-11-01 14:50 UTC, annarosesmarti requested changes

2023-11-01 14:50 UTC, annarosesmarti commented on src/components/CharacterList/CharaterList.test.tsx
> +import GlobalStyles from "../../styles/GlobalStyles";
eliminar si no hacen nada

2023-11-01 14:50 UTC, annarosesmarti commented on src/components/CharacterList/CharacterListStyle.ts
> +const CharacterListSyled = styled.ul`
ojo con CharacterListStyled

2023-11-01 14:55 UTC, annarosesmarti approved these changes

2023-11-01 14:56 UTC, barbara28bgb approved these changes

2023-11-01 14:56 UTC, merged