Add home page tsx, styled, test
isdi-coders-2023/ConejosVoladores-202309-bcn pull request #18
Opened 2023-10-31 18:59 UTC by barbara28bgb

2023-10-31 20:34 UTC, bigotes0invisibles requested changes
No estás haciendo el test está como una función cerrada

2023-10-31 20:34 UTC, bigotes0invisibles commented on src/pages/HomePage/HomePage.test.tsx
> +    test("Then it should show heading with text Character");
Aquí tienes un test vacio

2023-10-31 21:50 UTC, HugoVS26 approved these changes, later dismissed

2023-11-01 09:50 UTC, bigotes0invisibles requested changes

2023-11-01 09:50 UTC, bigotes0invisibles commented on src/pages/HomePage/HomePage.test.tsx
> +    test("Then it should show heading with text Character");
no tiene el segundo parametro

2023-11-01 09:50 UTC, bigotes0invisibles commented on src/pages/HomePage/HomePage.test.tsx
> +
ponerlo en una funcion  beforeEach antes de hacer el test para no tener problemas en un futuro

2023-11-01 09:50 UTC, bigotes0invisibles commented on src/components/App/AppStyled.ts
se ha repetido el Appstyle borra el archivo y cambia <AppStyled> yo ya me encargo con el mio

2023-11-01 09:52 UTC, annarosesmarti requested changes

2023-11-01 09:52 UTC, annarosesmarti commented on package.json
> +    "@vitest/coverage-v8": "^0.34.6",
tiene que ir en dependencias de desarrollo, no en dependencias

2023-11-01 09:52 UTC, annarosesmarti commented on src/components/App/AppStyled.ts
> +export default AppStyled;
falta un enter

2023-11-01 09:52 UTC, annarosesmarti commented on src/pages/HomePage/HomePageStyled.ts
> +  font-family: ${({ theme }) => theme.typography["mainFontFamily"]};
ojo que es el secondaryFontFamily

2023-11-01 09:52 UTC, annarosesmarti commented on src/components/App/AppStyled.ts
> +const AppStyled = styled.div`
este está repetido en main, tiene que estar solo en main

2023-11-01 09:52 UTC, annarosesmarti commented on src/styles/GlobalStyles.ts
> +    height: 100 vw;
modificar a vh sobra espacio entre 100 y vh

2023-11-01 09:52 UTC, annarosesmarti commented on src/styles/GlobalStyles.ts
> +
eliminar este espacio

2023-11-01 09:52 UTC, annarosesmarti commented on src/styles/GlobalStyles.ts
> +    justify-content: space-between;
le falta padding 22 de los 2 laterales, (no añadir superior e inferior)

2023-11-01 13:18 UTC, bigotes0invisibles approved these changes, later dismissed

2023-11-01 13:18 UTC, annarosesmarti submitted a review, later dismissed

2023-11-01 13:24 UTC, annarosesmarti approved these changes

2023-11-01 13:24 UTC, bigotes0invisibles approved these changes

2023-11-01 13:24 UTC, annarosesmarti approved these changes

2023-11-01 13:24 UTC, merged