Feature/context characters
isdi-coders-2023/ConejosVoladores-202309-bcn pull request #8
Opened 2023-10-30 20:29 UTC by bigotes0invisibles

2023-10-30 22:15 UTC, annarosesmarti approved these changes, later dismissed

2023-10-30 22:15 UTC, annarosesmarti commented on src/features/characters/strore/CharactersContext.ts
> +  characters: CharacterStructure[];
por qué las [ ] ? estoy mirando en la demo de Mario y no hay.. Sorry porque no domino esta parte

2023-10-30 22:15 UTC, annarosesmarti commented on src/features/characters/strore/CharactersContext.ts
> +  loadCharacters: (characters: CharacterStructure[]) => void;
igual que el anterior

2023-10-30 22:32 UTC, bigotes0invisibles commented on src/features/characters/strore/CharactersContext.ts
> +  characters: CharacterStructure[];
Porque es una array de personajes y así en charactercard ,characterinfo, formcharacter no nos hacemos tantos problemas

2023-10-31 08:19 UTC, HugoVS26 requested changes
Te has olvidado del test!

2023-10-31 10:55 UTC, HugoVS26 approved these changes

2023-10-31 11:06 UTC, barbara28bgb approved these changes

2023-10-31 11:58 UTC, annarosesmarti approved these changes

2023-10-31 12:04 UTC, merged