Feature/main header component
isdi-coders-2023/ConejosVoladores-202309-bcn pull request #9
Opened 2023-10-30 20:53 UTC by annarosesmarti

2023-10-30 20:57 UTC, HugoVS26 approved these changes, later dismissed

2023-10-30 21:10 UTC, bigotes0invisibles approved these changes

2023-10-30 21:10 UTC, bigotes0invisibles commented on index.html
> +  <link rel="icon" type="image/svg+xml" href="/vite.svg" />
Que hace ese vite.svg?

2023-10-30 21:12 UTC, bigotes0invisibles requested changes
Linea 6 de index.html borra el vite.svg

2023-10-31 09:31 UTC, bigotes0invisibles submitted a review, later dismissed

2023-10-31 10:40 UTC, bigotes0invisibles submitted a review, later dismissed

2023-10-31 11:21 UTC, closed without merging